/**
 * ⚠️ AI-GENERATED CODE - DEMONSTRATION ONLY ⚠️
 * 
 * THIS CODE WAS GENERATED BY AI AND IS PROVIDED SOLELY AS A DEMONSTRATION.
 * IT IS NOT MEANT TO BE LEFT IN THE FINAL PRODUCT.
 * 
 */

import * as d3 from "d3";
import { Game } from "../types";

interface PriceRange {
    label: string;
    min: number;
    max: number;
}

interface ChartData {
    label: string;
    count: number;
}

export function initDummy(container: HTMLElement, data: Game[]): void {
    console.log("Dummy viz initialized");

    // Define price ranges
    const priceRanges: PriceRange[] = [
        { label: "Free", min: 0, max: 0.01 },
        { label: "$0-5", min: 0.01, max: 5 },
        { label: "$5-10", min: 5, max: 10 },
        { label: "$10-20", min: 10, max: 20 },
        { label: "$20-50", min: 20, max: 50 },
        { label: "$50+", min: 50, max: Infinity }
    ];

    // Count games in each price range
    const chartData: ChartData[] = priceRanges.map(range => ({
        label: range.label,
        count: data.filter(game => game.price >= range.min && game.price < range.max).length
    }));

    // Chart dimensions
    const margin = { top: 40, right: 20, bottom: 40, left: 50 };
    const width = 800 - margin.left - margin.right;
    const height = 300 - margin.top - margin.bottom;

    // Create SVG
    const svg = d3.select(container)
        .append("svg")
        .attr("width", width + margin.left + margin.right)
        .attr("height", height + margin.top + margin.bottom)
        .style("border", "1px solid #ccc");

    // Create main group
    const g = svg.append("g")
        .attr("transform", `translate(${margin.left},${margin.top})`);

    // Create scales
    const xScale = d3.scaleBand()
        .domain(chartData.map(d => d.label))
        .range([0, width])
        .padding(0.2);

    const yScale = d3.scaleLinear()
        .domain([0, d3.max(chartData, d => d.count) || 0])
        .range([height, 0]);

    // Create bars
    g.selectAll(".bar")
        .data(chartData)
        .enter()
        .append("rect")
        .attr("class", "bar")
        .attr("x", d => xScale(d.label) || 0)
        .attr("y", d => yScale(d.count))
        .attr("width", xScale.bandwidth())
        .attr("height", d => height - yScale(d.count))
        .attr("fill", "#4a90e2")
        .attr("stroke", "#2e5c8a");

    // Add value labels on bars
    g.selectAll(".bar-label")
        .data(chartData)
        .enter()
        .append("text")
        .attr("class", "bar-label")
        .attr("x", d => (xScale(d.label) || 0) + (xScale.bandwidth() / 2))
        .attr("y", d => yScale(d.count) - 5)
        .attr("text-anchor", "middle")
        .attr("font-size", "11")
        .attr("fill", "#666")
        .text(d => d.count);

    // Add X axis
    const xAxis = d3.axisBottom(xScale);
    g.append("g")
        .attr("transform", `translate(0,${height})`)
        .call(xAxis)
        .attr("font-size", "12")
        .attr("color", "#333");

    // Add Y axis
    const yAxis = d3.axisLeft(yScale);
    g.append("g")
        .call(yAxis)
        .attr("font-size", "12")
        .attr("color", "#333");

    // Add title
    svg.append("text")
        .attr("x", (width + margin.left + margin.right) / 2)
        .attr("y", 25)
        .attr("text-anchor", "middle")
        .attr("font-size", "16")
        .attr("font-weight", "bold")
        .attr("fill", "#333")
        .text("Game Price Distribution");
}
