/**
 * ⚠️ AI-GENERATED CODE - DEMONSTRATION ONLY ⚠️
 * 
 * THIS CODE WAS GENERATED BY AI AND IS PROVIDED SOLELY AS A DEMONSTRATION.
 * IT IS NOT MEANT TO BE LEFT IN THE FINAL PRODUCT.
 * 
 */

import { Game } from "../types";



export function initDummy(container: HTMLElement, data: Game[]): void {
    console.log("Dummy viz initialized");

    // Create a simple histogram of game prices
    const priceRanges = [
        { label: "Free", min: 0, max: 0.01 },
        { label: "$0-5", min: 0.01, max: 5 },
        { label: "$5-10", min: 5, max: 10 },
        { label: "$10-20", min: 10, max: 20 },
        { label: "$20-50", min: 20, max: 50 },
        { label: "$50+", min: 50, max: Infinity }
    ];

    // Count games in each price range
    const counts = priceRanges.map(range => 
        data.filter(game => game.price >= range.min && game.price < range.max).length
    );

    const maxCount = Math.max(...counts);
    const barHeight = 200;
    const barWidth = 50;
    const spacing = 20;
    const padding = 40;

    // Create SVG
    const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
    svg.setAttribute("width", String(padding * 2 + priceRanges.length * (barWidth + spacing)));
    svg.setAttribute("height", String(barHeight + padding * 2));
    svg.setAttribute("style", "border: 1px solid #ccc;");

    // Draw bars
    priceRanges.forEach((range, i) => {
        const count = counts[i];
        const height = (count / maxCount) * barHeight;
        const x = padding + i * (barWidth + spacing);
        const y = padding + barHeight - height;

        // Draw bar
        const rect = document.createElementNS("http://www.w3.org/2000/svg", "rect");
        rect.setAttribute("x", String(x));
        rect.setAttribute("y", String(y));
        rect.setAttribute("width", String(barWidth));
        rect.setAttribute("height", String(height));
        rect.setAttribute("fill", "#4a90e2");
        rect.setAttribute("stroke", "#2e5c8a");
        svg.appendChild(rect);

        // Draw label
        const text = document.createElementNS("http://www.w3.org/2000/svg", "text");
        text.setAttribute("x", String(x + barWidth / 2));
        text.setAttribute("y", String(padding + barHeight + 20));
        text.setAttribute("text-anchor", "middle");
        text.setAttribute("font-size", "12");
        text.setAttribute("fill", "#333");
        text.textContent = range.label;
        svg.appendChild(text);

        // Draw count label
        const countText = document.createElementNS("http://www.w3.org/2000/svg", "text");
        countText.setAttribute("x", String(x + barWidth / 2));
        countText.setAttribute("y", String(y - 5));
        countText.setAttribute("text-anchor", "middle");
        countText.setAttribute("font-size", "11");
        countText.setAttribute("fill", "#666");
        countText.textContent = String(count);
        svg.appendChild(countText);
    });

    // Draw title
    const title = document.createElementNS("http://www.w3.org/2000/svg", "text");
    title.setAttribute("x", String(padding + (priceRanges.length * (barWidth + spacing) - spacing) / 2));
    title.setAttribute("y", String(25));
    title.setAttribute("text-anchor", "middle");
    title.setAttribute("font-size", "16");
    title.setAttribute("font-weight", "bold");
    title.setAttribute("fill", "#ffffff");
    title.textContent = "Game Price Distribution";
    svg.appendChild(title);

    container.appendChild(svg);
}
